### ISSUE TITLE
How to use this component?

### ISSUE THREAD

**Issue by vfonic** [klclee/ember-cli-dropdown#2]
Hi,

I'm new to ember and trying to figure out how to use this component.

I have a `ticket` model which has an array of possible `status`es. This is my try (that doesn't work):

```js
{{drop-down content=['open', 'closed', 'waiting'] value=ticket.status optionValuePath="value" optionLabelPath="display"}}
```

**Comment by klclee** [comment]
The issue will be the `content` and `optionValuePath` `optionLabelPath` is not matching. The values of the option* properties is map to the object properties of the content array so using, the example you have, `content` needs to be a array of objects (either in your component or controller):

```javascript
contentArray: [ {value: 'open', display: 'Open'}, {value:'closed', display:'Closed'}, {value:'waiting', display:'Waiting'}]
```  
(or it can be a array of `Ember.Object`)

then in your hbs:

```hbs
{{drop-down content=contentArray value=ticket.status optionValuePath="value" optionLabelPath="display"}}
```
